# Generated by Django 5.2.6 on 2025-10-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('absolute_magnitude', models.FloatField(blank=True, null=True)),
                ('estimated_diameter_min_km', models.FloatField(blank=True, null=True)),
                ('estimated_diameter_max_km', models.FloatField(blank=True, null=True)),
                ('is_potentially_hazardous', models.BooleanField(default=False)),
                ('close_approach_date', models.DateField(blank=True, null=True)),
                ('relative_velocity_kmh', models.FloatField(blank=True, null=True)),
                ('miss_distance_km', models.FloatField(blank=True, null=True)),
                ('orbiting_body', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asteroid',
                'verbose_name_plural': 'Asteroids',
                'ordering': ['-close_approach_date'],
            },
        ),
    ]
