# Generated by Django 5.2.6 on 2025-10-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usgs_id', models.CharField(max_length=100, unique=True)),
                ('magnitude', models.FloatField()),
                ('place', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth_km', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('tsunami', models.BooleanField(default=False)),
                ('felt_reports', models.IntegerField(blank=True, null=True)),
                ('significance', models.IntegerField(blank=True, null=True)),
                ('alert_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Earthquake',
                'verbose_name_plural': 'Earthquakes',
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='asteroid',
            name='ascending_node_deg',
            field=models.FloatField(blank=True, help_text='Longitude of ascending node', null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='eccentricity',
            field=models.FloatField(blank=True, help_text='Orbital eccentricity (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='inclination_deg',
            field=models.FloatField(blank=True, help_text='Inclination in degrees', null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='mean_anomaly_deg',
            field=models.FloatField(blank=True, help_text='Mean anomaly at epoch', null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='orbital_period_days',
            field=models.FloatField(blank=True, help_text='Orbital period in days', null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='periapsis_arg_deg',
            field=models.FloatField(blank=True, help_text='Argument of periapsis', null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='semi_major_axis_au',
            field=models.FloatField(blank=True, help_text='Semi-major axis in AU', null=True),
        ),
    ]
