# Generated by Django 5.2.7 on 2025-10-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_earthquake_asteroid_ascending_node_deg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='crater_diameter_km',
            field=models.FloatField(blank=True, help_text='Estimated crater diameter in km', null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='impact_energy_megatons',
            field=models.FloatField(blank=True, help_text='Estimated impact energy in megatons', null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='impact_probability',
            field=models.FloatField(default=0.0, help_text='Probability of impact (0-1)'),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='predicted_impact_latitude',
            field=models.FloatField(blank=True, help_text='Predicted impact latitude', null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='predicted_impact_location',
            field=models.CharField(blank=True, help_text='Human-readable impact location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='predicted_impact_longitude',
            field=models.FloatField(blank=True, help_text='Predicted impact longitude', null=True),
        ),
    ]
