# Generated by Django 5.2.7 on 2025-10-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_asteroid_crater_diameter_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='close_approach_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
